name: circbuf
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: run tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dcircbuf_build_tests=ON -Dcircbuf_enable_asan=${{ matrix.asan }} .
          cmake --build . -j 4
          ctest --verbose
