name: circbuf
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
        exclude:
          - asan: ON
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: setup dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y gcc-13 g++-13
          echo "CC=gcc-13" >> $GITHUB_ENV
          echo "CXX=g++-13" >> $GITHUB_ENV
      - name: run tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dcircbuf_build_tests=ON -Dcircbuf_enable_asan=${{ matrix.asan }} .
          cmake --build . -j 4
          ctest --verbose
